
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ExpressionInitAND ATRIB DIV EQ GEQ GT ID LCBracket LEQ LT MOD MULT NEQ NOT NUM OR RCBracket SUB SUMExpressionInit : AtribsAtribs : Atrib ';'\n              | Atribs Atrib ';'Atrib : ID ATRIB ExpreExpre : Expre SUM Expre\n             | Expre SUB Expre\n             | Expre MULT Expre\n             | Expre DIV Expre\n             | Expre MOD ExpreExpre : IDExpre : NUM"
    
_lr_action_items = {'ID':([0,2,6,7,8,12,13,14,15,16,],[4,4,-2,9,-3,9,9,9,9,9,]),'$end':([1,2,6,8,],[0,-1,-2,-3,]),';':([3,5,9,10,11,17,18,19,20,21,],[6,8,-10,-4,-11,-5,-6,-7,-8,-9,]),'ATRIB':([4,],[7,]),'NUM':([7,12,13,14,15,16,],[11,11,11,11,11,11,]),'SUM':([9,10,11,17,18,19,20,21,],[-10,12,-11,12,12,12,12,12,]),'SUB':([9,10,11,17,18,19,20,21,],[-10,13,-11,13,13,13,13,13,]),'MULT':([9,10,11,17,18,19,20,21,],[-10,14,-11,14,14,14,14,14,]),'DIV':([9,10,11,17,18,19,20,21,],[-10,15,-11,15,15,15,15,15,]),'MOD':([9,10,11,17,18,19,20,21,],[-10,16,-11,16,16,16,16,16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ExpressionInit':([0,],[1,]),'Atribs':([0,],[2,]),'Atrib':([0,2,],[3,5,]),'Expre':([7,12,13,14,15,16,],[10,17,18,19,20,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ExpressionInit","S'",1,None,None,None),
  ('ExpressionInit -> Atribs','ExpressionInit',1,'p_Expression_Init','yacc.py',8),
  ('Atribs -> Atrib ;','Atribs',2,'p_Atribs','yacc.py',12),
  ('Atribs -> Atribs Atrib ;','Atribs',3,'p_Atribs','yacc.py',13),
  ('Atrib -> ID ATRIB Expre','Atrib',3,'p_Atrib','yacc.py',20),
  ('Expre -> Expre SUM Expre','Expre',3,'p_Expre','yacc.py',32),
  ('Expre -> Expre SUB Expre','Expre',3,'p_Expre','yacc.py',33),
  ('Expre -> Expre MULT Expre','Expre',3,'p_Expre','yacc.py',34),
  ('Expre -> Expre DIV Expre','Expre',3,'p_Expre','yacc.py',35),
  ('Expre -> Expre MOD Expre','Expre',3,'p_Expre','yacc.py',36),
  ('Expre -> ID','Expre',1,'p_Expre_ID','yacc.py',40),
  ('Expre -> NUM','Expre',1,'p_Expre_NUM','yacc.py',44),
]
